# https://github.com/zaozaoniao/Redis-sentinel-with-docker-compose/blob/master/redisclientApp-independentNetwork/sentinel/docker-compose.yml

version: '3.7'

services:
     
  redis-master:
    image: redis:6-alpine
    volumes:
      - "./.data:/data"
    ports:
      - "6379:6379"
 
  redis-slave:
    image: redis:6-alpine
    command: redis-server --slaveof redis-master 6379
    links:
      - redis-master
    volumes:
      - "./.data:/data"
     
  # Instance 1
  redis-sentinel:
    build: 
      context: ./redis-sentinel
    links:
      - redis-master
    ports:
      - 26379:26379
 
  # Instance 2
  redis-sentinel2:
    build: 
      context: ./redis-sentinel
    links:
      - redis-master
    ports:
      - 26380:26379
 
  # Instance 3
  redis-sentinel3:
    build: 
      context: ./redis-sentinel
    links:
      - redis-master
    ports:
      - 26381:26379
